INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Transmisiones_03','Piso -1','Centro Tecnológico Mecánica','-1/03.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_de_Bancos_04B','Piso -1','Centro Tecnológico Mecánica','-1/04B.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_016','Piso -1','Centro Tecnológico Mecánica','-1/16.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Multiuso_05_A','Piso -1','Centro Tecnológico Mecánica','-1/05A.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Diganostico_Electronico_015','Piso -1','Centro Tecnológico Mecánica','-1/015.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Dinamometro_de_Rodillo_08','Piso -1','Centro Tecnológico Mecánica','-1/08.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Mecánica_Reconstruncuciones_De_Motos_04A','Piso -1','Centro Tecnológico Mecánica','-1/04A.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Mecánica_Multiuso_05B2','Piso -1','Centro Tecnológico Mecánica','-1/05B2.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Multiuso_05_B','Piso -1','Centro Tecnológico Mecánica','-1/05B.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_de_Estaciones_Motos_06','Piso -1','Centro Tecnológico Mecánica','-1/TMM09.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Lineas_de_Inspección_019','Piso -1','Centro Tecnológico Mecánica','-1/03.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Pañol Mecánica','Piso -1','Centro Tecnológico Mecánica Pañol','-1/PAÑOL3MECANICA.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_MVP_TMM01','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM01.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Maquinaria_TMM_02','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM02.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_MVP_08','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM08.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Mont_y_Mant_Ind_TMM_03','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM03.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Maquinaria_TMM_09','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM09.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Soldaduras_TMM_06','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM06.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_010','Piso -1','Centro Tecnológico de Maquinaria','-1/010.png');
-- INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_018','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM09.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Sala_013','Piso -1','Centro Tecnológico de Maquinaria','-1/013.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_de_Ensayos_TMM_04','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM04.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Lab._De_Inyección_TMM_05','Piso -1','Centro Tecnológico de Maquinaria','-1/TMM05.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Pañol_Maquinaria','Piso -1','Centro Tecnológico de Maquinaria Pañol','-1/PAÑOL2MAQYMANT.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Sala_de_Primeros_Auxilios','Piso -1','Sala de Primeros Auxilio','-1/PRIMEROSAUXILIOS.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Capilla_Sede','Piso 1','Capilla Sede','1/capilla.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Centro_Servicios_Académicos','Piso 1','Centro de Servicios Académicos','1/centroacademico.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Financiamiento_y_Dara','Piso 1','Financiamiento y Dara','1/financiamiento.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_101','Piso 1','Sala 101','1/101.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Caja','Piso 1','Caja Sede','1/caja.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Pastoral_y_Punto_Estudiantil','Piso 1','Pastoral y Punto Estudiantil','1/pastoral.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Auditorio','Piso 2','Auditorio','auditorio.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Centro_Fotocopiado','Piso 2','Centro Fotocopiado','centrofotocopiado.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Biblioteca','Piso 2','Biblioteca','biblioteca.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_211','Piso 2','Sala 211','211.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Programas_Transversales: Matemática, Lenguaje, Inglés, Innovación y emprendimiento, Ética y Formación Cristiana','Piso 2','Programas_Transversales: Matemática, Lenguaje, Inglés, Innovación y emprendimiento, Ética y Formación Cristiana','oftransversales.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_201','Piso 2','Sala 201','201.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_202','Piso 2','Sala 202','202.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_203','Piso 2','Sala 203','203.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_204','Piso 2','Sala 204','204.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Servicios_digitales','Piso 3','Servicios digitales','cetecom.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L1','Piso 3','Laborarorio de Computación L1','L1.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L2','Piso 3','Laborarorio de Computación L2','L2.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L3','Piso 3','Laborarorio de Computación L3','L3.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L4','Piso 3','Laborarorio de Computación L4','L4.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L5','Piso 3','Laborarorio de Computación L5','L5.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L6','Piso 3','Laborarorio de Computación L6','L6.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L7','Piso 3','Laborarorio de Computación L7','L7.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L10','Piso 3','Laborarorio de Computación L10','L10.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L8','Piso 3','Laborarorio de Computación L8','L8.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Centro_Innova','Piso 3','Centro Innova','304.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_302','Piso 3','Laboratorio Autotronica III y IV','302.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Circuito_Electrico._Y_Software','Piso 3','Centro Tecnológico Electricidad','303.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_Instalaciones_Elect._E_Ilumin._312','Piso 3','Centro Tecnológico Electricidad','312.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_Autotronica_I_y_II_305A','Piso 3','Laboratorio Autotronica I y II 305A','305A.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Circ._Elect._Y_Softw 305B','Piso 3','Centro Tecnológico Electricidad','305B.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Centro de aprendizaje industria 4.0','Piso 3','Centro Tecnológico Electricidad','306.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio Smart_Grid','Piso 3','Centro Tecnológico Electricidad','307.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_PLC_y_Redes_Ind._308','Piso 3','Centro Tecnológico Electricidad','308.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Proyectos_CTEEA_309','Piso 3','Centro Tecnológico Electricidad','309.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_Maquinas_Elect._310','Piso 3','Centro Tecnológico Electricidad 1','310.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Hidraulica_y_Neum._311','Piso 3','Centro Tecnológico Electricidad','311.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Pañol_Electricidad','Piso 3','Centro Tecnológico Electricidad Pañol','panol3.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_314','Piso 3','Sala 314','314.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_315','Piso 3','Sala 315','315.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Dirección_Sede','Piso 4',' Dirección Sede','DIRECCIONSEDE.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Coordinación_Docente','Piso 4','Coordinación Docente','COORDINACIONDOCENTE.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','UAP','Piso 4','UAP','UAP.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_de_Odontologia_416','Piso 4','Centro Tecnológico Salud','416.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizacion_III_401','Piso 4','Centro Tecnológico Salud','401.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Pabellon_402_B','Piso 4','Centro Tecnológico Salud','402B.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Sala_Ambulatorio_402_A','Piso 4','Centro Tecnológico Salud','402A.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizacion_II_404','Piso 4','Centro Tecnológico Salud','404.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Neonatologia_405','Piso 4','Centro Tecnológico Salud','405.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Debriging_406','Piso 4','Centro Tecnológico Salud','406.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizado_I_407','Piso 4','Centro Tecnológico Salud','407.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Quimica_y_Farmacia_408','Piso 4','Centro Tecnológico Salud','408.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Banco_de_Sangre_409','Piso 4','Centro Tecnológico Salud','409.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Clínico_410','Piso 4','Centro Tecnológico Salud','410.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Anatomía_411','Piso 4','Centro Tecnológico Salud','411.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Ciencias_Básicas_412','Piso 4','Centro Tecnológico Salud','412.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizado_IV_413','Piso 4','Centro Tecnológico Salud','413.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_415','Piso 4','Sala 415','415.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_417','Piso 4','Sala 417','417.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_418','Piso 4','Sala 418','418.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_505','Piso 5','Sala 505','505.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_506','Piso 5','Sala 506','506.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_508','Piso 5','Sala 508','508.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_510','Piso 5','Sala 510','510.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_511','Piso 5','Sala 511','511.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_501','Piso 5','Sala 501','501.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_502','Piso 5','Sala 502','502.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_503','Piso 5','Sala 503','503.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_504','Piso 5','Sala 504','504.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Terraza','Terraza','Piso 5','Terraza','TERRAZAPISO5.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_605','Piso 6','Sala 605','605.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_606','Piso 6','Sala 606','606.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_607','Piso 6','Sala 607','607.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_608','Piso 6','Sala 608','608.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_609','Piso 6','Sala 609','609.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_601','Piso 6','Sala 601','601.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_602','Piso 6','Sala 602','602.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_603','Piso 6','Sala 603','603.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_604','Piso 6','Sala 604','604.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_705','Piso 7','Sala 705','705.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_706','Piso 7','Sala 706','706.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_708','Piso 7','Sala 708','708.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_709','Piso 7','Sala 709','709.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_701','Piso 7','Sala 701','701.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_702','Piso 7','Sala 702','702.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_703','Piso 7','Sala 703','703.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_704','Piso 7','Sala 704','704.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','CITT','Piso 8','CITT','CITT.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_806','Piso 8','Sala 806','806.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L9','Piso 8','Laboratorio L9','L9.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_805','Piso 8','Sala 805','805.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Sala_L804_Thinking_&_Proyect','Piso 8','Sala 804','804.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Pañol','Pañol_de_Conectividad_y_Redes','Piso 8','Pañol de Conectividad y Redes','8PANOLCONECTIVIDADYREDES.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_LCCNA_Taller_de_Hardware','Piso 8','Laboratorio LCCNA','8LCCNA.png');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Taller_de_Telecomunicaciones_LTR','Piso 8','Taller LTR','8LTR.png');
