INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (10,'MAYRA CONTRERAS','Programa Transversales', 'Jefa del Programa de Lenguaje');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (20,'CRISTIAN BARRA','Director de carreras', 'Ing. en informática, Analista Programador Computacional, Ing. en Conectividad y Redes');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (30,'GUSTAVO BULNES','Director de carreras', 'Ingeniería y Técnico en Electricidad y Automatización Industrial ');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (40,'JOSE DONOSO','Director de carreras', 'Técnico en Energías Renovables y Técnico en Mecánica Automotriz y Autotrónica');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (50,'MAURICIO SULANTAY','Director de carreras', 'Técnico de Radiodiagnóstico y Radioterapia en Química y Farmacia, Técnico de Laboratorio Clínico y Banco de Sangre');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (60,'ANDRES CARRASCO','Programa Transversales', 'Jefe del Programa de Ética y Formación');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (70,'VALERIA CERDA','Programa Transversales', 'Jefa del Programa de Matemática');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (80,'DANIELA DE LA IGLESIA','Directora de carreras', 'Informática Biomédica y Técnico en Odontología');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (90,'NANCY JARA','Programa Transversales', 'Jefe del Programa de Innovación y Emprendimiento');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (100,'KEILA LAGOS','Directora de carreras', 'Técnico de Enfermería');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (110,'PATRICIA GALVEZ','Programa Transversales', 'Jefa del Programa de Inglés');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (120,'SERGIO NEGRETE','-------', '----------');
INSERT INTO jefatura (id, nombre, descripcion, glosa) VALUES (130,'CRISTIAN CAVIERES','Director de carreras', 'Maquinaria y Vehiculos Pesados, Mantenimiento Electromecánico');

INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17379775-3','ROMINA ANDREA BUSTOS GOMEZ','ROM.BUSTOSG@PROFESOR.DUOC.CL','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12.163.625-5','FERNANDO RAFAEL SAN MARTIN  WOERNER','fe.sanmartinw@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16246491-4','JOHNY ALEJANDRO GONZALEZ  SEGUEL','JOHN.GONZALEZ@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12880966-K','JUAN MAURICIO NAVARRETE GONZALEZ','jua.navarreteg@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('20142488-7','JAVIERA RUTH MARTINEZ CARRERA','javie.martinezc@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13653130-1','JAVIER ANDRES JELDRES MALDONADO','ja.jeldres@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16938837-7','MANUEL ALEJANDRO GALVEZ DURAN','MAN.DURANG@PROFESOR.DUOC.CL','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('25559625-K','JORGE AUGUSTO NIOCHET DIAZ','JO.NIOCHET@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13672216-6','JUAN PABLO CISTERNAS FORTUNE','jua.cisternasf@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18860424-2','FERNANDA  VILLALOBOS NUÑEZ','fe.villalobosn@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13460535-9','ELIANA MALLEN GONZALEZ GONZALEZ','elia.gonzalezg@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9846118-3','SANDRA EMILIA MUÑOZ  TORRES','S.MUNOZT@PROFESOR.DUOC.CL','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('8815826-1','EUGENIO ALEXIS PAREDES  MARTEL','EU.PAREDES@PROFESOR.DUOC.CL','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18188617-K','FELIPE NICOLAS FUENZALIDA JARA','fe.fuenzalidaj@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13459315-6','FRANCISCO ANTONIO GALDAMES ACOSTA','FR.GALDAMESA@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16007157-5','NICOLAS ALONSO CONTRERAS MEDINA','NICOL.CONTRERASM@PROFESOR.DUOC.CL','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12123192-1','MARILUZ ALEJANDRA RODRIGUEZ DONOSO','MAR.RODRIGUEZD@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12827819-2','ALEJANDRO ANDRES ESPINOZA  NUÑEZ','ALE.ESPINOZAN@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18832675-7','MATIAS SEBASTIAN AEDO MOYA','MAT.AEDOM@PROFESOR.DUOC.CL','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15743634-1','TAMARA ANDREA ALVAREZ RAMIREZ','TAM.ALVAREZ@PROFESOR.DUOC.CL','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19056698-6','DIEGO RAUL PEREIRA SALAS','DIE.PEREIRAS@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19529491-7','VICTOR HUGO GALLARDO VALDES','vic.gallardov@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('25194775-9','RAFAEL ANGEL DEGRAVES ','RA.DEGRAVES@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19525638-1','VANESSA ALEXANDRA ZUÑIGA PEREZ','van.zunigap@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18006865-1','PABLO ESTEBAN ARAYA FUENTES','P.ARAYA@PROFESOR.DUOC.CL','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17008143-9','DENISE LEONOR MONTES  MARTINEZ','D.MONTES@PROFESOR.DUOC.CL','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('11267135-8','ROSA NOEMI CABEZAS GUERRERO','ROS.CABEZAS@PROFESOR.DUOC.CL','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16909500-0','CRISTIAN IGNACIO MOLINA ESPINOZA','','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13469017-4','CLAUDIO ALEJANDRO MIRANDA MUÑOZ','CL.MIRANDAM@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18047500-1','JONATHAN GERMAN VILLALOBOS ESCOBAR','JON.VILLALOBOS@PROFESOR.DUOC.CL','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16720329-9','HUGO ANDRES BARRIOS  MIRANDA','','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17023724-2','JUAN CARLOS ABARCA SEREÑO','ju.abarcas@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('11601745-8','PATRICIO ESTEBAN ABARCA MALDONADO','pa.abarca@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14279014-9','ERWIN ENRIQUE AGUILERA SEGURA','erw.aguilera@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13093560-5','JOSE LUIS AHUMADA GARCIA','jos.ahumadag@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16220939-6','JOSE FRANCISCO ALARCON LIZAMA','JOSE.ALARCON@PROFESOR.DUOC.CL','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('25277735-0','CARLOS ALBERTO ALBORNOZ PACHECO','CAR.ALBORNOZ@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17244650-7','PAMELA EDITH ALMENDRA MARTINEZ','p.almendra@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18089752-6','DANIELA CAMILA ALMONACID CABEZAS','da.almonacidc@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('8430715-7','TERESA CECILIA ALVARADO VILLARREAL','t.alvarado@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19323671-5','IGNACIO ANDRES ALVAREZ CATALAN','IG.ALVAREZC@PROFESOR.DUOC.CL','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10359274-7','CLAUDIA ANDREA ALVAREZ ROJAS','c.alvarezro@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13504584-5','PAULA ANDREA ALVAREZ REYES','pa.alvarezr@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19078042-2','FRANCISCA SOFIA ARANCIBIA VALDEBENITO','fr.arancibiav@profesor.duoc.cl','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12490839-6','EDUARDO MARCELO ARANCIBIA GUZMAN','E.ARANCIBIA@PROFESOR.DUOC.CL','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18092686-0','CONSTANZA NICOLE ARANCIBIA SANDOVAL','con.arancibia@profesor.duoc.cl','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18407138-K','CRISTOPHER ANDRES ARCOS SANDOVAL','c.arcoss@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18907371-2','PALOMA ROCIO ARELLANO CARDENAS','PAL.ARELLANO@PROFESOR.DUOC.CL','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15842420-7','ROXANA ANGELICA AREVALO IBAÑEZ','roxa.arevalo@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17386244-K','LEONARDO JAVIER ARIAS QUEZADA','LE.ARIASQ@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12561721-2','GUSTAVO ALEJANDRO ARIAS BECERRA','g.ariasb@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10199365-5','RICARDO ANDRES ARREDONDO ZELADA','rica.arredondo@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13830063-3','GISELLE SOLANGE ASTUDILLO CAVIERES','gis.astudillo@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('11481478-4','RAQUEL ALEJANDRA BARAHONA RUIZ','raqu.barahona@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9570332-1','JOSE EDUARDO BARRAZA VARAS','jos.barraza@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14139132-1','ISRAEL ANDRES BARRERA BUSTOS','i.barrera@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16145754-K','TATIANA ANDREA BASCUÑAN CARRERA','ta.bascunan@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('26148791-8','NANCY BAUTISTA AVILA','NA.BAUTISTA@PROFESOR.DUOC.CL','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('6547822-6','ALEJANDRO JAIME BELMAR ARROYO','al.belmar@profesor.duoc.cl','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10146483-0','BERNARDO RAIMUNDO BERTOLOTTO PALACIOS','be.bertolotto@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14009585-0','SANTIAGO ANDRES BOZA PINTO','sa.boza@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('25896062-9','OMAR JAVIER BULLONES  GIMENEZ','om.bullones@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13064901-7','FABIAN ANDRES CABRERA TOLEDO','fabi.cabrera@profesor.duoc.cl','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16396795-2','SEBASTIAN ANDRES CALLEJAS FAJARDO','s.callejas@profesor.duoc.cl','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13483551-6','FELIPE GABRIEL CAMPOS OJEDA','fe.camposo@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14045256-4','RODRIGO ANTONIO CANDIA VALENZUELA','r.candiav@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('6260169-8','RICARDO IGNACIO CAÑETE CLAVERO','ri.canete@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18119709-9','GERARDO GABRIEL CARO SALAZAR','g.caros@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14384307-6','CRISTIAN ALEJANDRO CARREÑO SALINAS','cr.carrenos@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('11405840-8','MAURICIO ENRIQUE CARRERA LEIVA','MAU.CARRERA@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15655075-2','EBER GERARDO CARVAJAL VALDEBENITO','eb.carvajal@profesor.duoc.cl','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16942340-7','MELISSA ANDREA CARVAJAL GUZMAN','me.carvajal@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17072225-6','JOSE IGNACIO CASTAÑEDA MORALES','JO.CASTANEDAM@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12085381-3','LUIS ORLANDO CASTRO VELIZ','luis.castr@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13834111-9','CRISTIAN IGNACIO CATALAN STUARDO','cr.catalans@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('27103379-6','EDIXON IVAN COLMENAREZ LOPEZ','ed.colmenarez@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17832957-K','FELIPE IGNACIO CONCHA MANCILLA','F.CONCHA@PROFESOR.DUOC.CL','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19837560-8','ELISA VALERIA CONEJERO ABRIGO','el.conejero@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16656415-8','JORGE FELIPE CONTRERAS DAZA','JOR.CONTRERASD@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18742228-0','SEBASTIAN ONOFRE CONTRERAS BRAVO','S.CONTRERASB@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15739598-K','ALEXANDRA CORNEJO MEJIAS','a.cornejom@profesor.duoc.cl','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19172027-k','TANIA VALERIA CORTES ROQUE','T.CORTES@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12856374-1','ANGELICA MARIA CORTES COLLADO','an.cortesc@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16767421-6','NATALIA SOLEDAD CORTES CAMPOS','n.cortesc@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16725528-0','JOHNNATHAN RENE CUBILLOS FLORES','jo.cubillosf@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9696656-3','ERIKA MAGDALENA CUBILLOS TAPIA','e.cubillt@profesor.duoc.cl','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14120134-4','REBECA INES DIAZ WENBORNE','reb.diaz@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13933576-7','RAMON FRANCISCO DIAZ VERDUGO','ram.diazv@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16945674-7','FRANCISCO JAVIER DIAZ  QUIJADA ','fra.diazq@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10437494-8','GABRIELA  DIAZ-MUÑOZ IHMAIDAN','g.diazmunoz@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('8445958-5','APOSTOL ANGEL DIMITROPULOS RODRIGUEZ','a.dimitropu@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14154726-7','FELIPE ESTEBAN DURAN NAVARRETE','f.durann@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9685388-2','FRANCISCO JAVIER DUSSUEL MUHLHAUSER','f.dussuel@profesor.duoc.cl','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16068201-9','KATHERINE  ENCINA ALARCON ','K.ENCINA@PROFESOR.DUOC.CL','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('23657704-K','CLAUDIA MARCELA ESCOBAR OSORIO','cl.escobaro@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18247903-9','CRISTOBAL IGNACIO ESCUDERO   CONTRERAS','cr.escudero@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18243687-9','MARCOS ANDRES ESPINOZA MENDEZ','marco.espinozam@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17864743-1','MARCELO ALEJANDRO FERNANDEZ SILVA','MARC.FERNANDEZS@PROFESOR.DUOC.CL','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13714958-3','INGRID IRAIDA FLORES SALGADO','ing.flores@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15355922-8','PABLO GABRIEL FREDES DONOSO','pabl.fredes@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17951097-9','ALEJANDRO DANIEL FREIRE ORELLANA','al.freire@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15314149-5','NATHALIE PATRICIA FUENTES ALTEZ','nath.fuentes@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13467157-2','FABIOLA GEORGINA FUENTES SAN MARTIN','fa.fuentess@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('22456314-0','ISAAC ANDRES GALASSI OYARZUN','I.GALASSI@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10333228-1','ANDREA VIVIANA GALAZ VILCHES','AND.GALAZ@PROFESOR.DUOC.CL','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9386341-0','VICTOR EMILIO GALLEGUILLOS CRUZ','vic.galleguill@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9008561-1','PABLO ALEJANDRO GALVEZ VALENCIA','pa.galvezv@profesor.duoc.cl','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('7542968-1','EULOGIO IVAN GARAY FABRES','e.garay@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15344419-6','RODRIGO ANDRES GARRIDO MILLAS','ro.garridom@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16207137-8','VICTORIA ALEJANDRA GODOY GARRIDO','v.godoyg@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18159112-9','GUSTAVO DAVID GOMEZ POTENZA','g.gomez@profesor.duoc.cl','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('8539197-6','MIGUEL AUGUSTO GONZALEZ STUARDO','mia.gonzalez@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13280715-9','FELIPE ALBERTO GONZALEZ BAEZA','FELI.GONZALEZ@PROFESOR.DUOC.CL','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17872405-3','MICHAEL LUIS GONZALEZ MARAMBIO','M.GONZALEZMA@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10156368-5','CRISTIAN EDUARDO GONZALEZ GATICA','c.gonzalezga@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17265548-3','SEBASTIAN ALONSO GONZALEZ ALVAREZ','s.gonzalezal@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15936168-3','NATALIA ANDREA GONZALEZ MARTINEZ','nata.gonzalezm@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15617503-K','ANDRES ELIAS GUTIERREZ RUIZ','an.gutierrezr@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13039343-8','KAREN DENISE HAHN ROJAS','KA.HAHNR@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15662963-4','PAOLA ANDREA HENRIQUEZ DIAZ','paol.henriquez@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18347846-K','FERNANDO ISRAEL HERRERA MENA','fern.herreram@profesor.duoc.cl','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17325657-4','DIEGO ALFREDO HORMAZABAL BRUHN','d.hormazabal@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('20467654-2','MANUEL IGNACIO HUEICHAQUEO LETELIER','ma.hueichaqueo@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17941517-8','ARIEL ANIBAL ILLANES SEGURA','ari.illanes@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10544277-7','RAFAEL MAURICIO INOSTROZA FARIAS','RA.INOSTROZA@PROFESOR.DUOC.CL','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18604261-1','FERNANDA CAMILA JAÑA CASTILLO','fern.jana@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17832945-6','IGNACIO SEBASTIAN JARA CONTRERAS','ig.jarac@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16691805-7','JOSE SANTOS JARA FUENTES','jo.jaraf@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16330202-0','JOCELIN ANDREA JOFRE SEGUEL','joce.jofre@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12668339-1','RODRIGO ALBERTO JORQUERA VERGARA','rodr.jorquera@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10682402-9','FELIPE ANDRES JORQUERA BRAVO','feli.jorquera@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('8651977-1','RAUL ISIDORO LADRON DE GUEVARA SAN MARTNI','r.ladrondeguev@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13811797-9','FELIPE MAURICIO LAMBERT CARO','FE.LAMBERT@PROFESOR.DUOC.CL','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15451099-0','ALVARO ESTEBAN LIBERONA PACHECO','a.liberona@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18081209-1','LAURA IGNACIA LIZANA MORALES','la.lizana@profesor.duoc.cl','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14143413-6','FELIPE ANDRES LIZANA BASTIAS','F.LIZANA@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12724787-0','JOSÉ ABELINO LIZANA GODOY','j.lizanag@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18156484-9','CAROL IVON LIZANA ROJAS','caro.lizana@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12367954-7','OSWIN ANTONIO LOPEZ NUÑEZ','osw.lopez@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15646862-2','MARIA JOSE LOPEZ CASTAÑEDA','m.lopezca@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15344142-1','SUSANA SOFIA LOPEZ GARRIDO','susa.lopez@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12428937-8','MANUEL ALEJANDRO MADARIAGA LOPEZ','m.madariagal@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15785830-0','DANILO ESTEBAN MALDONADO GONZALEZ','DAN.MALDONADOG@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9617462-4','OSVALDO PATRICIO MALDONADO PINTO','osv.maldonado@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16361018-3','ANICE YESMIN MALUJE VILLANUEVA','A.MALUJE@PROFESOR.DUOC.CL','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15794758-3','ELIAS ANTON MARIPIL HIDALGO','e.maripil@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('25672140-6','JOHON EDUARDO MARQUEZ  PINILLA','joh.marquez@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16020186-K','ENRIQUE ANTONIO MARTINEZ ORTEGA','e.martinez@profesor.duoc.cl','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('7699158-8','MARIA TERESA MATAMALA ULLOA','M.MATAMALA@PROFESOR.DUOC.CL','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15366931-7','GABRIEL ANTONIO MATURANA ALBORNOZ','gab.maturana@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15437573-2','JUDITH MAYORGA VALERIA','j.mayorga@profesor.duoc.cl','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16228987-K','SERGIO ANDRES MEDINA RUIZ','se.medinar@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16170236-6','JUAN PAULO MEDINA LEAL','ju.medinal@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15841789-8','FRANCISCA MONTSERRAT MENA VEGA','fra.mena@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18246750-2','YLIAM COSME GONZALO MENCIA RIVERA','y.mencia@profesor.duoc.cl','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18409301-4','BASTIAN KEVIN MENDOZA ALVAREZ','BAS.MENDOZA@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13923377-8','MAURICIO ENRIQUE MORA FRIEDL','MA.MORAF@PROFESOR.DUOC.CL','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19055338-8','BENJAMIN ELIAS MORA TORRES','bej.mora@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18223144-4','MARCELO ERASMO MORA ARAVENA','m.mora@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15067410-7','LESLY ELIZABETH MORA  LOPEZ','LES.MORA@PROFESOR.DUOC.CL','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13444771-0','ANA LORENA MOYA ISAMITT','an.moya@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15123234-5','TRINIDAD NATALIA MUJICA TORRES','t.mujica@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('6191703-9','JOSE DANIEL MUNAR ANDRADE','j.munar@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('11122684-9','LEONARDO OSVALDO MUÑOZ VILLALON','leon.munozv@profesor.duoc.cl','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18953042-0','CAMILO ALEXIS FELIPE MUÑOZ MONTOYA','ca.felipe@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18695305-3','JUAN CARLOS MUÑOZ VERA','j.munozve@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16080484-K','OMAR PAVEL MUÑOZ CUYOTUPAC','om.munoz@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16769013-0','JEAN NICOLAS MUÑOZ FERNANDEZ','jea.munozf@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('7516796-2','LUIS EDUARDO MUÑOZ MENDEZ','l.munoz@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18126854-9','DANIELA FERNANDA MUÑOZ VILLANUEVA','d.munoz@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15716143-1','IRIS NADIA NAVARRETE YAÑEZ','i.navarrete@profesor.duoc.cl','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15466583-8','FRANCISCA JAVIERA NAVARRO CARRASCO','franc.navarro@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15085384-2','CARLA PATRICIA NAVIA ORDENES','ca.navia@profesor.duoc.cl','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16710850-4','DANIELA VERONICA NORAMBUENA YAÑEZ','d.norambuena@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15660491-7','CARLOS ALBERTO NUÑEZ URIBE','c.nunezu@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15923359-6','ANDREA STEPHANIE NUÑEZ GUTIERREZ','an.nunezg@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16567585-1','ALFREDO ANDRES NUÑEZ ARANDA','alf.nunez@profesor.duoc.cl','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17704526-8','NAHIM DURAYTS OGSAEN GONZALEZ','n.ogsaen@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12253087-6','CLAUDIA ANDREA ORELLANA LAGOS','clau.orella@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13197864-2','FRANCISCO ERNESTO ORELLANA VIDAL','fr.orellanav@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17546050-0','MANUEL EDUARDO ORTUBIA ARENAS','ma.ortubia@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13484943-6','LEONOR HERMINDA PALMA SEGUEL','leo.palma@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('11257566-9','PATRICIO IGNACIO PALMA  MUÑOZ','pat.palmam@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13726619-9','MONICA NATHALIA PANES MARTINEZ','m.panes@profesor.duoc.cl','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12235877-1','JAIME GONZALO PARRA MONTOYA','ja.parram@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16109231-2','JUAN PABLO PAYERO DÍAZ','j.payero@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16839737-2','CESAR ALONSO PEÑA SERRANO','CESA.PENA@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17768727-8','RODRIGO ANDRES PINTO OLAVE','ro.pintoo@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19111791-3','JESSICA ANDREA PIZARRO PARRA','JE.PIZARRO@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13692504-0','ALFONSO ANDRES POBLETE MORAN','ALF.POBLETE@PROFESOR.DUOC.CL','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19229372-3','IGNACIO GUILLERMO QUIROZ CASAS','ign.quirozc@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16919906-K','BASTIAN DAVID QUIROZ PARRA','b.quirozp@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15726464-8','ALVARO JAVIER RAVAZZANO ROMERO','a.ravazzano@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16265728-3','ANDRES ANTONIO REYES CARTAGENA','an.reyes@profesor.duoc.cl','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13770236-3','DANIEL ENRIQUE RIQUELME RIGOT','dae.riquelme@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16742923-8','VICTOR ANDRES ROBLERO ROJAS','vi.roblero@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17822895-1','CAMILA CONSTANZA RODRIGUEZ ALARCON','C.RODRIGUEZA@PROFESOR.DUOC.CL','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9174373-6','MARIA CRISTINA RODRIGUEZ ESPINOZA','m.rodrigueze@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18115196-K','JAVIERA FRANCISCA ROJAS NUÑEZ','JA.ROJASN@PROFESOR.DUOC.CL','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16377384-8','CARLA FERNANDA ROJAS ARAVENA','C.ROJAS4@PROFESOR.DUOC.CL','Docente',null,60,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13832756-6','VALENTINA JOSE ROJAS WALBAUM','val.rojas@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16570885-7','DAVATA ZUNY ROJAS MUÑOZ','d.rojasm@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('20100412-8','FERNANDA IGNACIA ROJAS ESPINOZA','FE.ROJASE@PROFESOR.DUOC.CL','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18750030-3','LEONARDO ANTONIO ROMERO AGUILERA','LE.ROMEROA@PROFESOR.DUOC.CL','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10675936-7','JUAN ORLANDO RORE GUAJARDO','ju.rore@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13757752-6','IVAN RAUL ROSALES ALARCON','I.ROSALES@PROFESOR.DUOC.CL','Docente',null,90,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18446618-K','JOSE ANTONIO RUIZ-TAGLE MATURANA','J.RUIZTAGLE@PROFESOR.DUOC.CL','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17053512-K','AARON NAIN RUMINOT ORELLANA','A.RUMINOT@PROFESOR.DUOC.CL','Docente',null,10,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15329790-8','RODRIGO ALEXIS SALAS MOYANO','rodr.salasm@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16044527-0','MARIA JOSE SALAZAR ROJAS','m.salazarr@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('7882103-5','MARIA EUGENIA SALAZAR JARA','m.salazarj@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('9257081-9','JOSE MIGUEL SALINAS GAJARDO','jo.salinas@profesor.duoc.cl','Docente',null,120,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18268561-5','CRISTOPHER BYRON ELLIOT SALVO BOROA','cr.elliot@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12241594-5','CARMEN GLORIA SALVO INOSTROZA','car.salvo@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('25527956-4','EDWIN ORLANDO SANCHEZ VALDERRAMA','edw.sanchez@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13942085-3','FELIPE SIXTO SANDOVAL RAMOS','F.SANDOVALR@PROFESOR.DUOC.CL','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18078618-K','FRANCO JESUS SANGUINETTI VILCHES','fr.sanguinetti@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17022769-7','ABRAHAM ALEXIS SEPULVEDA VENEGAS','ab.sepulvedav@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18356661-K','MARCO ANDREAS SILVA BAEZ','m.silvab@profesor.duoc.cl','Docente',null,50,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18862331-k','FABIAN ANDRES SILVA OLIVARES','f.silvao@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('25220936-0','VIVIANA MARCELA SOTO VASQUEZ','vivi.soto@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19057408-3','NICOLAS ANDRES SOTO RETAMAL','N.SOTOR@PROFESOR.DUOC.CL','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16855102-9','EMILIO GONZALO SOTO ROJAS','emil.soto@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('8548238-6','PATRICIO ANDRES SOTO SERDIO','patr.soto@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13281174-1','MELISA DANIELA TAPIA CUEVAS','me.tapiac@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16483867-6','ISABEL DEL PILAR TAPIA GUAJARDO','i.tapiag@profesor.duoc.cl','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13253538-8','CLAUDIA MARIA TORO REYES','cla.toror@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18251933-2','JOSE IGNACIO TORO GARCIA','JOSE.TORO@PROFESOR.DUOC.CL','Docente',null,70,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18606942-0','FRANCISCO ALEJANDRO TORRES CABALLERO','f.torresca@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('7745856-5','SERGIO ENRIQUE URIBE LEPPE','se.uribe@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15183547-3','FREDY MAURICIO UTRERAS FUENTES','F.UTRERAS@PROFESOR.DUOC.CL','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13831848-6','URSULA ALEJANDRA VALDEBENITO SILVA','ur.valdebenito@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('19354635-8','DIEGO RODRIGO VALENCIA ROMAN','DI.VALENCIARO@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('13906932-3','ELIZABETH YAMILET VALENZUELA MANQUE','eliza.valenzue@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18487612-4','GONZALO PATRICIO VALENZUELA PIÑEIRO','g.valenzuelapi@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('14312614-5','GABRIEL EDUARDO VALLEJOS YAÑEZ','ga.vallej@profesor.duoc.cl','Docente',null,30,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18400759-2','DANIEL ALEJANDRO VARGAS QUINTEROS','dan.vargas@profesor.duoc.cl','Docente',null,110,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17099523-6','YOHANA MARGOT VEJAR LEAL','yo.vejar@profesor.duoc.cl','Docente',null,130,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16586430-1','ERNESTO LEONIDAS VELASQUEZ VELASQUEZ','E.VELASQUEZ@PROFESOR.DUOC.CL','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15894383-2','ESTEBAN DE JESUS VERA CORTEZ','es.verac@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('16710396-0','PASCAL MARIANA VERA GALDAMES','pas.vera@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('18402429-2','GUILLERMO MATIAS  VILLACURA  TORRES','gu.villacura@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17403185-1','DANIELA DE LOURDES VON KRETSCHMANN SAN MARTIN','d.vonkretschma@profesor.duoc.cl ','Docente',null,80,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('15904361-4','ROSA EDITH YAÑEZ MALDONADO','ro.yanez@profesor.duoc.cl','Docente',null,100,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('12056253-3','FELICIANO DEL CARMEN ZAMORANO QUIROZ','feli.zamorano@profesor.duoc.cl','Docente',null,40,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('10125382-1','ALEX ULISES ZUÑIGA MONTIEL','al.zuiga@profesor.duoc.cl','Docente',null,20,null, null);
INSERT INTO personal (run, nombre, correo, cargo, ubicacion, jefatura, puesto, imagen) VALUES ('17023844-3','ALFONSO IGNACIO ZUÑIGA ACOSTA','alfo.zuniga@profesor.duoc.cl','Docente',null,40,null, null);
