INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Transmisiones_03','Piso -1','Centro Tecnológico Mecánica','image1.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_de_Bancos_04B','Piso -1','Centro Tecnológico Mecánica','image2.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_016','Piso -1','Centro Tecnológico Mecánica','image3.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Multiuso_05_A','Piso -1','Centro Tecnológico Mecánica','image4.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Diganostico_Electronico_015','Piso -1','Centro Tecnológico Mecánica','image5.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Dinamometro_de_Rodillo_08','Piso -1','Centro Tecnológico Mecánica','image6.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Mec._Reconst._De_Motos_04A','Piso -1','Centro Tecnológico Mecánica','image7.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Mec._Multiuso_05B2','Piso -1','Centro Tecnológico Mecánica','image8.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Multiuso_05_B','Piso -1','Centro Tecnológico Mecánica','image9.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_de_Estaciones_Motos_06','Piso -1','Centro Tecnológico Mecánica','image10.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Taller_Lineas_de_Inspección_019','Piso -1','Centro Tecnológico Mecánica','image11.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Mecánica','Pañol','Piso -1','Centro Tecnológico Mecánica Pañol','image12.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_MVP_TMM01','Piso -1','Centro Tecnológico de Maquinaria','image13.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Maquinaria_TMM_02','Piso -1','Centro Tecnológico de Maquinaria','image14.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_MVP_08','Piso -1','Centro Tecnológico de Maquinaria','image15.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Mont_y_Mant_Ind_TMM_03','Piso -1','Centro Tecnológico de Maquinaria','image16.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Maquinaria_TMM_09','Piso -1','Centro Tecnológico de Maquinaria','image17.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Soldaduras_TMM_06','Piso -1','Centro Tecnológico de Maquinaria','image18.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_010','Piso -1','Centro Tecnológico de Maquinaria','image19.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_018','Piso -1','Centro Tecnológico de Maquinaria','image20.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Sala_013','Piso -1','Centro Tecnológico de Maquinaria','image21.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_de_Ensayos_TMM_04','Piso -1','Centro Tecnológico de Maquinaria','image22.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Taller_Lab._De_Inyección_TMM_05','Piso -1','Centro Tecnológico de Maquinaria','image23.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Maquinaria','Pañol_Maquinaria','Piso -1','Centro Tecnológico de Maquinaria Pañol','image24.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Sala_de_Primeros_Auxilios','Piso -1','Sala de Primeros Auxilio','image25.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Capilla_Sede','Piso 1','Capilla Sede','image26.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Centro_Servicios_Académicos','Piso 1','Centro de Servicios Académicos','image27.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Financiamiento_y_Dara','Piso 1','Financiamiento y Dara','image28.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_101','Piso 1','Sala 101','image29.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Caja','Piso 1','Caja Sede','image30.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Pastoral_y_Punto_Estudiantil','Piso 1','Pastoral y Punto Estudiantil','image31.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Centro_Fotocopiado','Piso 2','Centro Fotocopiado','image32.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Biblioteca','Piso 2','Biblioteca','image33.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_211','Piso 2','Sala 211','image34.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Oficina_Transversales','Piso 2','Oficina Transversales','image35.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_201','Piso 2','Sala 201','image36.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_202','Piso 2','Sala 202','image37.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_203','Piso 2','Sala 203','image38.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_204','Piso 2','Sala 204','image39.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Cetecom','Piso 3','Cetecom','image40.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L1','Piso 3','Laborarorio de Computación L1','image41.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L2','Piso 3','Laborarorio de Computación L2','image42.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L3','Piso 3','Laborarorio de Computación L3','image43.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L4','Piso 3','Laborarorio de Computación L4','image44.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L5','Piso 3','Laborarorio de Computación L5','image45.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L6','Piso 3','Laborarorio de Computación L6','image46.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L7','Piso 3','Laborarorio de Computación L7','image47.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L10','Piso 3','Laborarorio de Computación L10','image48.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L8','Piso 3','Laborarorio de Computación L8','image49.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Desing_Factory','Piso 3','Desin Factory','image50.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_302','Piso 3','Laboratorio Autotronica III y IV','image51.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Circuito_Elec._Y_Softw_303','Piso 3','Centro Tecnológico Electricidad','image52.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_Instalaciones_Elect._E_Ilumin._312','Piso 3','Centro Tecnológico Electricidad','image53.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_Autotronica_I_y_II_305A','Piso 3','Laboratorio Autotronica I y II 305A','image54.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Circ._Elect._Y_Softw 305B','Piso 3','Centro Tecnológico Electricidad','image55.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Industria_4.0_306','Piso 3','Centro Tecnológico Electricidad','image56.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Smart_Grid_307','Piso 3','Centro Tecnológico Electricidad','image57.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_PLC_y_Redes_Ind._308','Piso 3','Centro Tecnológico Electricidad','image58.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Proyectos_CTEEA_309','Piso 3','Centro Tecnológico Electricidad','image59.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_Maquinas_Elect._310','Piso 3','Centro Tecnológico Electricidad 1','image60.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Laboratorio_de_Hidraulica_y_Neum._311','Piso 3','Centro Tecnológico Electricidad','image61.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Electricidad','Pañol_Electricidad','Piso 3','Centro Tecnológico Electricidad Pañol','image62.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_314','Pios 3','Sala 314','image63.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_315','Pios 3','Sala 315','image64.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Dirección_Sede','Piso 4',' Dirección Sede','image65.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','Coordinación_Docente','Piso 4','Coordinación Docente','image66.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','UAP','Piso 4','UAP','image67.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_de_Odontologia_416','Piso 4','Centro Tecnológico Salud','image68.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizacion_III_401','Piso 4','Centro Tecnológico Salud','image69.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Pabellon_402_B','Piso 4','Centro Tecnológico Salud','image70.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Sala_Ambulatorio_402_A','Piso 4','Centro Tecnológico Salud','image71.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizacion_II_404','Piso 4','Centro Tecnológico Salud','image72.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Neonatologia_405','Piso 4','Centro Tecnológico Salud','image73.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Debriging_406','Piso 4','Centro Tecnológico Salud','image74.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizado_I_407','Piso 4','Centro Tecnológico Salud','image75.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Quimica_y_Farmacia_408','Piso 4','Centro Tecnológico Salud','image76.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Banco_de_Sangre_409','Piso 4','Centro Tecnológico Salud','image77.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Clínico_410','Piso 4','Centro Tecnológico Salud','image78.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Anatomía_411','Piso 4','Centro Tecnológico Salud','image79.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Ciencias_Básicas_412','Piso 4','Centro Tecnológico Salud','image80.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Taller de Salud','Laboratorio_Hospitalizado_IV_413','Piso 4','Centro Tecnológico Salud','image81.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_415','Piso 4','Sala 415','image82.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_417','Piso 4','Sala 417','image83.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_418','Piso 4','Sala 418','image84.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_505','Piso 5','Sala 505','image85.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_506','Piso 5','Sala 506','image86.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_508','Piso 5','Sala 508','image87.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_510','Piso 5','Sala 510','image88.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_511','Piso 5','Sala 511','image89.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_501','Piso 5','Sala 501','image90.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_502','Piso 5','Sala 502','image91.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_503','Piso 5','Sala 503','image92.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_504','Piso 5','Sala 504','image93.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Terraza','Terraza','Piso 5','Terraza','image94.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_605','Piso 6','Sala 605','image95.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_606','Piso 6','Sala 606','image96.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_607','Piso 6','Sala 607','image97.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_608','Piso 6','Sala 608','image98.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_609','Piso 6','Sala 609','image99.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_601','Piso 6','Sala 601','image100.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_602','Piso 6','Sala 602','image101.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_603','Piso 6','Sala 603','image102.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_604','Piso 6','Sala 604','image103.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_705','Piso 7','Sala 705','image104.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_706','Piso 7','Sala 706','image105.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_708','Piso 7','Sala 708','image106.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_709','Piso 7','Sala 709','image107.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_701','Piso 7','Sala 701','image108.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_702','Piso 7','Sala 702','image109.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_703','Piso 7','Sala 703','image110.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_704','Piso 7','Sala 704','image111.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Oficinas','CITT','Piso 8','CITT','image112.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_806','Piso 8','Sala 806','image113.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_L9','Piso 8','Laboratorio L9','image114.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Salas','Sala_805','Piso 8','Sala 805','image115.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Sala_L804_Thinking_&_Proyect','Piso 8','Sala 804','image116.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Pañol','Pañol_de_Conectividad_y_Redes','Piso 8','Pañol de Conectividad y Redes','image117.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Laboratorio_LCCNA_Taller_de_Hardware','Piso 8','Laboratorio LCCNA','image118.jpg');
INSERT INTO sector (ubicacion, nombre, piso, descripcion, imagen) VALUES('Laboratorio','Taller_de_Telecomunicaciones_LTR','Piso 8','Taller LTR','image119.jpg');
